In [2]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('exemplo2.csv')
df.head()

idade  conta_corrente risco
0  21.257389      783.127911  ruim
1  21.766573      979.747521   bom
2  25.321033     1065.328054  ruim
3  23.919268     1195.758078   bom
4  21.805298     1083.764450   bom

In [ ]:
from sklearn.svm import SVC
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X = df.drop('risco', axis=1)
y = df.risco

norm = MinMaxScaler()
X_norm = norm.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_norm, y, train_size=2/3, random_state=1)

svc = SVC(kernel='poly')
svc.fit(X_train, y_train)

accuracy_score(y_test, svc.predict(X_test))

In [20]:
df2 = pd.read_csv('exemplo3.csv')
df2.head()

idade  conta_corrente       sexo risco
0  21.257389      783.127911  masculino  ruim
1  21.766573      979.747521   feminino   bom
2  25.321033     1065.328054   feminino   bom
3  23.919268     1195.758078   feminino   bom
4  21.805298     1083.764450   feminino   bom

In [26]:
X = df2.drop('risco', axis=1)
y = df2.risco
X.select_dtypes(include='object')

sexo
0     masculino
1      feminino
2      feminino
3      feminino
4      feminino
...         ...
2495   feminino
2496  masculino
2497  masculino
2498  masculino
2499  masculino

[2500 rows x 1 columns]

In [33]:
from sklearn.preprocessing import OneHotEncoder

X_cat = X.select_dtypes(include='object')

onehot = OneHotEncoder(sparse=False, drop='first')
X_bin = onehot.fit_transform(X_cat)
X_bin

array([[1.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

In [39]:
from sklearn.preprocessing import MinMaxScaler

X_num = X.select_dtypes(exclude='object')
minmax = MinMaxScaler()
X_num = minmax.fit_transform(X_num)

array([[0.05586473, 0.06720224],
       [0.06499436, 0.09938945],
       [0.12872564, 0.11339923],
       ...,
       [0.85424954, 0.36522222],
       [0.62401886, 0.42781034],
       [0.61473291, 0.54031447]])

In [41]:
import numpy as np 

X_all = np.append(X_num, X_bin, axis=1)
X_all

array([[0.05586473, 0.06720224, 1.        ],
       [0.06499436, 0.09938945, 0.        ],
       [0.12872564, 0.11339923, 0.        ],
       ...,
       [0.85424954, 0.36522222, 1.        ],
       [0.62401886, 0.42781034, 1.        ],
       [0.61473291, 0.54031447, 1.        ]])

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X_all, y, train_size=2/3, random_state=42)

svc2 = SVC()
svc2.fit(X_train, y_train)

accuracy_score(y_test, svc2.predict(X_test))

0.7146282973621103